version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/inpostack-public-web
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/inpostack-public-web
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
      timeout: 30
      runas: ubuntu
